---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certs/
  - server/

commonLabels:
  app.kubernetes.io/name: cockroach

images:
  - name: cockroach-init
    newName: quay.io/webhippie/alpine
    newTag: "3.21"
  - name: cockroach-server
    newName: cockroachdb/cockroach
    newTag: "v25.1.1"

...
