---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certs/
  - server/

commonLabels:
  app.kubernetes.io/name: cockroach

images:
  - name: cockroach-init
    newName: docker.io/webhippie/alpine
    newTag: "3.10"
  - name: cockroach-server
    newName: docker.io/cockroachdb/cockroach
    newTag: "v20.2.8"

...
