---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: cockroach-server

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cockroach-server

subjects:
  - kind: ServiceAccount
    name: cockroach-server

...
