---
apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: cockroach-server

spec:
  replicas: 3
  serviceName: cockroach-server
  podManagementPolicy: Parallel

  updateStrategy:
    type: RollingUpdate

  template:
    spec:
      serviceAccountName: cockroach-server
      enableServiceLinks: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 60

      initContainers:
        - name: certs
          image: cockroach-init
          imagePullPolicy: IfNotPresent

          command:
            - sh
            - -c
            - |
              cp /node/* /certs/
              chmod 0400 /certs/*.key

          volumeMounts:
            - name: certs
              mountPath: /certs/
            - name: secret
              mountPath: /node/

      containers:
        - name: server
          image: cockroach-server
          imagePullPolicy: IfNotPresent

          command:
            - /cockroach/cockroach
            - start
            - --logtostderr=WARNING
            - --certs-dir=/cockroach/cockroach-certs/
            - --http-host=0.0.0.0
            - --advertise-host=$(PODNAME).cockroach-server.$(NAMESPACE).svc.cluster.local
            - --join=cockroach-server-0.cockroach-server.$(NAMESPACE).svc.cluster.local
            - --cache=25%
            - --max-sql-memory=25%

          env:
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

            - name: COCKROACH_CHANNEL
              value: kubernetes-insecure

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 26257
              protocol: TCP

          # resources:
          #   requests:
          #     cpu: "0.1"
          #     memory: "256Mi"
          #   limits:
          #     cpu: "0.5"
          #     memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: http

          readinessProbe:
            httpGet:
              path: /health?ready=1
              port: http

          volumeMounts:
            - name: data
              mountPath: /cockroach/cockroach-data
            - name: certs
              mountPath: /cockroach/cockroach-certs/

      volumes:
        - name: certs
          emptyDir: {}
        - name: secret
          projected:
            sources:
              - secret:
                  name: cockroach-server
                  items:
                    - key: tls.crt
                      path: node.crt
                      mode: 0400
                    - key: tls.key
                      path: node.key
                      mode: 0400
              - secret:
                  name: cockroach-client
                  items:
                    - key: tls.crt
                      path: client.root.crt
                      mode: 0400
                    - key: tls.key
                      path: client.root.key
                      mode: 0400
              - secret:
                  name: cockroach-ca
                  items:
                    - key: ca.crt
                      path: ca.crt
                      mode: 0400

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

...
